### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by brodavi** [zcanter/aframe-gradient-sky#3]
I have tried using `<a-animation>` as well as `https://www.npmjs.com/package/aframe-animation-component` to animate the `topColor` and `bottomColor` attributes, without success. The attribute gets set by the `from` attribute in the animation element/component, but doesn't change.

**Comment by zcanter** [comment]
Yeah I am ultimately a designer who codes what he can, but I'll take a look at it. I have to update the documentation, but in order to change the color after the element is build you need to add this:

`material="shader: gradient; topColor: x x x; bottomColor: x x x"`

Like I said though I am really not very experienced with Node or NPM but I appreciate you letting me know these issues. I will work on them tonight. Feel free to give it a shot and give me a pull request if you figure it out.

**Comment by zcanter** [comment]
Okay so upon further research and testing it appears this issue is due to the `<a-animation>` component. The A-Frame team is considering deprecating it all together: https://github.com/aframevr/aframe/issues/1927.

I will work on a color animation fix. I also invite anyone who has any ideas on this to give it a go!

**Comment by zcanter** [comment]
Okay solved it:

You do need to use [aframe-animation-component](https://github.com/ngokevin/kframe/tree/master/components/animation).

The code to animate could then look something like this:

`<a-gradient-sky material="shader: gradient; topColor: 255 0 0; bottomColor: 0 121 255;"
        animation="property: material.topColor; dur: 1000; to: 0 244 0"";></a-gradient-sky>`

**Comment by brodavi** [comment]
Awesome thanks! :)
